export const SET_USER_SELECTED_LOADING = "SET_USER_SELECTED_LOADING";
export const SET_USER_SELECTED_SUCCESS = "SET_USER_SELECTED_SUCCESS";
export const SET_USER_SELECTED_FAILURE = "SET_USER_SELECTED_FAILURE";
